export const TOPIC_TIME_PER_QUESTION: Record<string, Record<string, number>> = {
  Mathematics: {
    "Trigonometry": 100,
    "Integration": 135,
    "Circles": 100,
    "Probability": 100,
    "Definite Integrals": 100,
    "Complex Numbers": 75,
    "Properties of Triangles": 75,
    "Differential Equations": 100,
    "Limits & Continuity": 75,
    "Straight Lines": 75,
    "Matrices & Determinants": 75,
    "Permutations & Combinations": 75,
    "Tangents & Normals": 75,
    "Quadratic Equations": 75,
    "Differentiation": 75,
    "Functions": 65,
    "Binomial Theorem": 65,
    "Random Variables": 75,
    "Vector Addition": 65,
    "Theory of Equations": 75,
    "Hyperbola": 75,
    "Pair of Straight Lines": 75,
    "Cross Product": 65,
    "Maxima & Minima": 75,
    "3D Geometry": 65,
    "Ellipse": 75,
    "Parabola": 75,
    "Plane": 65,
    "Dot Product": 65,
    "Hyperbolic Functions": 75,
    "Statistics": 45,
    "Locus": 65,
    "Partial Fractions": 65,
    "Areas": 75,
    "System of Circles": 75,
    "Multiple Angles": 75,
    "De Moivre’s Theorem": 75,
    "DC & DR": 75,
  },
  Physics: {
    "Thermodynamics": 105,
    "Rotational Motion": 105,
    "Moving Charges & Magnetism": 105,
    "Work Power Energy": 95,
    "Oscillations": 95,
    "Semiconductors": 45,
    "Current Electricity": 105,
    "Electrostatics": 105,
    "Friction": 85,
    "Atomic Physics": 65,
    "Electric Charges & Fields": 95,
    "Thermal Properties": 80,
    "KTG": 80,
    "Motion in Straight Line": 65,
    "Alternating Current": 95,
    "EM Waves": 45,
    "Gravitation": 80,
    "Fluids": 80,
    "Nuclear Physics": 45,
    "Ray Optics": 95,
    "Units & Measurements": 45,
    "Wave Optics": 95,
    "Communication": 45,
    "EMI": 95,
    "Solids": 45,
    "Wave Motion": 95,
    "Magnetism & Matter": 80,
    "Motion in Plane": 80,
    "Dual Nature": 65,
    "Vectors": 45,
  },
  Chemistry: {
    "Thermodynamics": 75,
    "Chemical Kinetics": 75,
    "States of Matter": 75,
    "Biomolecules": 45,
    "Chemical Equilibrium": 75,
    "Solutions": 75,
    "Atomic Structure": 75,
    "Haloalkanes & Haloarenes": 65,
    "Surface Chemistry": 45,
    "Chemical Bonding": 75,
    "Carbon Family": 45,
    "Periodic Table": 45,
    "d & f Block": 45,
    "Coordination Compounds": 75,
    "Organic (C,H,O)": 65,
    "Carbonyl Compounds": 65,
    "Carboxylic Acids": 65,
    "Hydrocarbons": 65,
    "Nitrogen Compounds": 65,
    "Polymers": 45,
    "Metallurgy": 45,
    "s-block": 45,
    "Stoichiometry": 75,
    "GOC": 75,
    "Everyday Chemistry": 45,
    "Hydrogen": 45,
    "Boron Family": 45,
    "Solid State": 45,
  },
  Botany: {
    "Diversity": 45,
    "Plant Kingdom": 45,
    "Cell Structure": 65,
    "Cell Division": 75,
    "Biomolecules": 45,
    "Photosynthesis": 75,
    "Respiration": 75,
    "Reproduction": 75,
    "Inheritance": 105,
    "Molecular Basis": 105,
    "Biotechnology": 75,
    "Morphology": 45,
    "Plant Growth": 75,
    "Transport": 75,
    "Evolution": 65,
    "Food Production": 45,
    "Microbes": 45,
    "Organisms & Populations": 45,
    "Ecosystem": 45,
    "Biodiversity": 45,
    "Environmental Issues": 45,
  },
  Zoology: {
    "Animal Kingdom": 75,
    "Digestion": 75,
    "Breathing": 75,
    "Circulation": 75,
    "Excretion": 75,
    "Neural Control": 75,
    "Hormonal": 75,
    "Reproduction": 75,
    "Genetics": 105,
    "Health & Disease": 75,
    "Biotechnology": 75,
    "Structural Organisation": 65,
    "Locomotion": 65,
    "Evolution": 65,
    "Applied Biology": 45,
    "Reproductive Health": 45,
    "Organisms & Population": 45,
    "Biomolecules": 45,
  }
};

export const DEFAULT_TIME_PER_QUESTION = 75;

export function getBaseTime(subject: string, topic: string): number {
  const subjectMap = TOPIC_TIME_PER_QUESTION[subject];
  if (!subjectMap) return DEFAULT_TIME_PER_QUESTION * 20;

  // Exact match or loosely normalized match
  const time = subjectMap[topic] || Object.entries(subjectMap).find(([k]) => 
    k.toLowerCase().replace(/[^a-z0-9]/g, "") === topic.toLowerCase().replace(/[^a-z0-9]/g, "")
  )?.[1] || DEFAULT_TIME_PER_QUESTION;

  return time * 20;
}

export function getAttemptTargetTime(baseTime: number, attempt: number): number {
  switch (attempt) {
    case 1: return baseTime + 120;
    case 2: return baseTime;
    case 3: return Math.round(baseTime * 0.85);
    case 4: return Math.round(baseTime * 0.70);
    default: return baseTime;
  }
}
